### ISSUE TITLE
Solidify plan for back end

### ISSUE THREAD

**Issue by gbarcelo** [HACC2018/The-Johnson-Family#6]
- Consider possible collection architectures, choose one for implementation
 - Consider possible data structure architectures for database wrapper class, choose one for implementation

**Comment by LE-AMRITA** [comment]
A great addition to our presentation for HACC the ability to identify the root cause and solution to the infestation.  See the link for visuals of what is good for a farm and what is
. https://www.google.com/search?q=broccoli+bugs+vs+bad+bugs+government+data+base&newwindow=1&safe=active&tbm=isch&tbo=u&source=univ&sa=X&ved=2ahUKEwirtfXSyLbeAhUDGDQIHQqaDxMQsAR6BAgFEAE&biw=1838&bih=1009
